plugins:
    - babel
    - import
env:
  es6: true
  node: true
extends: 
    - 'airbnb-base'
    - plugin:import/errors
    - plugin:import/warnings
rules:
  indent:
    - error
    - 2
    - { "SwitchCase": 1 } 
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-console: 0
